(require 'auto-complete)
(global-auto-complete-mode t)
(setq ac-auto-start 2)
;;(add-to-list 'ac-sources 'ac-source-yasnippet)
(setq-default ac-sources '(ac-source-filename ac-source-words-in-same-mode-buffers ac-source-yasnippet))
(require 'auto-complete-config)
(add-to-list 'ac-dictionary-directories "~/emacs/.emacs.d/elisp/ac-dict")
(ac-config-default)
;; (setq ac-auto-start nil)
(ac-set-trigger-key "TAB")
