;; (add-to-list 'custom-theme-load-path "~/.emacs.d/emacs-color-theme-solarized")
;; (add-to-list 'custom-theme-load-path "~/.emacs.d/molokai-theme")
;;(load-theme 'solarized-dark t)
;;(load-theme 'solarized-light t)
;;(load-theme 'deeper-blue t)
;;(load-theme 'misterioso t)
;;(load-theme 'molokai-theme t)
