;; windows用のフォント設定
(defvar japanese-font "VL Gothic")
 (set-default-font "VL Gothic-11")
(set-fontset-font nil 'jisx0201                 japanese-font)
(set-fontset-font nil 'latin-jisx0201           japanese-font)
(set-fontset-font nil 'japanese-jisx0208        japanese-font)
(set-fontset-font nil 'japanese-jisx0208-1978   japanese-font)
(set-fontset-font nil 'japanese-jisx0212        japanese-font)
(set-fontset-font nil 'japanese-jisx0213-1      japanese-font)
(set-fontset-font nil 'japanese-jisx0213-2      japanese-font)
(set-fontset-font nil 'japanese-jisx0213-a      japanese-font)
(set-fontset-font nil 'japanese-jisx0213.2004-1 japanese-font)
(set-fontset-font nil 'katakana-sjis            japanese-font)
(set-fontset-font nil 'cp932-2-byte             japanese-font)
(set-fontset-font nil 'cp932                    japanese-font)
(set-fontset-font nil '(#x3040 . #x309f)        japanese-font)
(set-fontset-font nil '(#x30a0 . #x30ff)        japanese-font)
(set-fontset-font nil '(#xff00 . #xffef)        japanese-font)
(set-fontset-font nil '(#x0370 . #x03ff)        japanese-font)
